// Sample appointment data for Max Hospital (hosp-3)
// This data can be imported to seed the appointments in AppContext

export const sampleAppointments = [
  {
    id: 'APT-00001',
    patient_id: 'PAT-1001',
    patientName: 'Rajesh Kumar',
    doctor_id: 'doctor-max-001',
    doctorId: 'doctor-max-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Anjali Mehta',
    department: 'Cardiology',
    date: '2026-02-15',
    time: '10:00 AM',
    reason: 'Routine cardiac checkup and blood pressure monitoring',
    consultationFee: 800,
    status: 'Upcoming',
    createdAt: '2026-02-13T08:30:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00002',
    patient_id: 'PAT-1002',
    patientName: 'Priya Sharma',
    doctor_id: 'doctor-max-002',
    doctorId: 'doctor-max-002',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Vikram Singh',
    department: 'Neurology',
    date: '2026-02-14',
    time: '11:30 AM',
    reason: 'Persistent headaches and dizziness',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-12T14:20:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00003',
    patient_id: 'PAT-1003',
    patientName: 'Amit Patel',
    doctor_id: 'doctor-max-003',
    doctorId: 'doctor-max-003',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Sneha Reddy',
    department: 'Orthopedics',
    date: '2026-02-14',
    time: '02:00 PM',
    reason: 'Knee pain and joint stiffness',
    consultationFee: 750,
    status: 'Upcoming',
    createdAt: '2026-02-13T10:15:00.000Z',
    uploadedMedicalFile: {
      fileName: 'x-ray-knee.pdf',
      mimeType: 'application/pdf',
      previewUrl: '',
    },
  },
  {
    id: 'APT-00004',
    patient_id: 'PAT-1004',
    patientName: 'Neha Gupta',
    doctor_id: 'doctor-max-004',
    doctorId: 'doctor-max-004',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Rahul Joshi',
    department: 'Dermatology',
    date: '2026-02-14',
    time: '03:30 PM',
    reason: 'Skin rash and allergic reaction',
    consultationFee: 650,
    status: 'Upcoming',
    createdAt: '2026-02-13T16:45:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00005',
    patient_id: 'PAT-1005',
    patientName: 'Sanjay Verma',
    doctor_id: 'doctor-max-005',
    doctorId: 'doctor-max-005',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Kavita Desai',
    department: 'Pulmonology',
    date: '2026-02-15',
    time: '09:00 AM',
    reason: 'Breathing difficulty and chest congestion',
    consultationFee: 850,
    status: 'Upcoming',
    createdAt: '2026-02-13T12:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00006',
    patient_id: 'PAT-1006',
    patientName: 'Anita Singh',
    doctor_id: 'doctor-max-006',
    doctorId: 'doctor-max-006',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Arjun Kapoor',
    department: 'Endocrinology',
    date: '2026-02-15',
    time: '11:00 AM',
    reason: 'Diabetes management and blood sugar control',
    consultationFee: 800,
    status: 'Upcoming',
    createdAt: '2026-02-12T09:30:00.000Z',
    uploadedMedicalFile: {
      fileName: 'blood-test-results.pdf',
      mimeType: 'application/pdf',
      previewUrl: '',
    },
  },
  {
    id: 'APT-00007',
    patient_id: 'PAT-1007',
    patientName: 'Vivek Malhotra',
    doctor_id: 'doctor-max-007',
    doctorId: 'doctor-max-007',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Pooja Nair',
    department: 'ENT',
    date: '2026-02-15',
    time: '02:30 PM',
    reason: 'Ear infection and hearing issues',
    consultationFee: 700,
    status: 'Upcoming',
    createdAt: '2026-02-13T15:20:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00008',
    patient_id: 'PAT-1008',
    patientName: 'Meera Iyer',
    doctor_id: 'doctor-max-008',
    doctorId: 'doctor-max-008',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Karan Chopra',
    department: 'General Medicine',
    date: '2026-02-16',
    time: '10:30 AM',
    reason: 'General health checkup and vaccination',
    consultationFee: 600,
    status: 'Upcoming',
    createdAt: '2026-02-13T11:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00009',
    patient_id: 'PAT-1002',
    patientName: 'Priya Sharma',
    doctor_id: 'doctor-max-009',
    doctorId: 'doctor-max-009',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Manish Agarwal',
    department: 'Gastroenterology',
    date: '2026-02-16',
    time: '01:00 PM',
    reason: 'Stomach pain and digestive issues',
    consultationFee: 750,
    status: 'Upcoming',
    createdAt: '2026-02-12T13:45:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00010',
    patient_id: 'PAT-1009',
    patientName: 'Rajesh Kumar',
    doctor_id: 'doctor-max-010',
    doctorId: 'doctor-max-010',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Sunita Rao',
    department: 'Ophthalmology',
    date: '2026-02-16',
    time: '03:00 PM',
    reason: 'Eye strain and vision problems',
    consultationFee: 700,
    status: 'Upcoming',
    createdAt: '2026-02-13T14:30:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00011',
    patient_id: 'PAT-1001',
    patientName: 'Rajesh Kumar',
    doctor_id: 'doctor-max-001',
    doctorId: 'doctor-max-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Anjali Mehta',
    department: 'Cardiology',
    date: '2026-02-10',
    time: '11:00 AM',
    reason: 'Follow-up cardiac consultation',
    consultationFee: 800,
    status: 'Completed',
    createdAt: '2026-02-08T09:15:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00012',
    patient_id: 'PAT-1003',
    patientName: 'Amit Patel',
    doctor_id: 'doctor-max-003',
    doctorId: 'doctor-max-003',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Sneha Reddy',
    department: 'Orthopedics',
    date: '2026-02-08',
    time: '10:00 AM',
    reason: 'Initial consultation for knee pain',
    consultationFee: 750,
    status: 'Completed',
    createdAt: '2026-02-06T10:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00013',
    patient_id: 'PAT-1010',
    patientName: 'Deepak Sharma',
    doctor_id: 'doctor-max-011',
    doctorId: 'doctor-max-011',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Ritu Malhotra',
    department: 'Pediatrics',
    date: '2026-02-12',
    time: '09:30 AM',
    reason: 'Child vaccination and growth checkup',
    consultationFee: 550,
    status: 'Completed',
    createdAt: '2026-02-10T08:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00014',
    patient_id: 'PAT-1011',
    patientName: 'Kavita Reddy',
    doctor_id: 'doctor-max-012',
    doctorId: 'doctor-max-012',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Anil Kumar',
    department: 'Urology',
    date: '2026-02-11',
    time: '02:00 PM',
    reason: 'Kidney stone consultation',
    consultationFee: 850,
    status: 'Cancelled',
    createdAt: '2026-02-09T11:30:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00015',
    patient_id: 'PAT-1002',
    patientName: 'Priya Sharma',
    doctor_id: 'doctor-max-002',
    doctorId: 'doctor-max-002',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Anjali Mehta',
    department: 'Cardiology',
    date: '2026-02-15',
    time: '02:00 PM',
    reason: 'Chest pain and palpitations',
    consultationFee: 800,
    status: 'Upcoming',
    createdAt: '2026-02-13T17:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00016',
    patient_id: 'PAT-1012',
    patientName: 'Arun Mehta',
    doctor_id: 'doctor-max-001',
    doctorId: 'doctor-max-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Anjali Mehta',
    department: 'Cardiology',
    date: '2026-02-17',
    time: '11:30 AM',
    reason: 'Post-surgery follow-up',
    consultationFee: 800,
    status: 'Upcoming',
    createdAt: '2026-02-14T09:00:00.000Z',
    uploadedMedicalFile: null,
  },
  // Dr. Garvit Pathania's Appointments - Neurology Department
  {
    id: 'APT-00017',
    patient_id: 'PAT-2001',
    patientName: 'Suresh Yadav',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-15',
    time: '09:00 AM',
    reason: 'Severe migraine and recurring headaches',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-14T08:00:00.000Z',
    uploadedMedicalFile: {
      fileName: 'mri-scan-brain.pdf',
      mimeType: 'application/pdf',
      previewUrl: '',
    },
  },
  {
    id: 'APT-00018',
    patient_id: 'PAT-2002',
    patientName: 'Anjali Verma',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-15',
    time: '11:00 AM',
    reason: 'Dizziness and balance issues',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-14T10:30:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00019',
    patient_id: 'PAT-2003',
    patientName: 'Rahul Kapoor',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-15',
    time: '02:30 PM',
    reason: 'Memory issues and cognitive assessment',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-13T15:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00020',
    patient_id: 'PAT-2004',
    patientName: 'Pooja Desai',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-15',
    time: '04:00 PM',
    reason: 'Numbness in hands and feet - neuropathy check',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-14T12:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00021',
    patient_id: 'PAT-2005',
    patientName: 'Vikram Malhotra',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-16',
    time: '10:00 AM',
    reason: 'Seizure disorder follow-up',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-14T14:00:00.000Z',
    uploadedMedicalFile: {
      fileName: 'eeg-report.pdf',
      mimeType: 'application/pdf',
      previewUrl: '',
    },
  },
  {
    id: 'APT-00022',
    patient_id: 'PAT-2006',
    patientName: 'Sneha Agarwal',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-17',
    time: '09:30 AM',
    reason: 'Tremors and movement disorder evaluation',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-13T09:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00023',
    patient_id: 'PAT-2007',
    patientName: 'Karan Singh',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-18',
    time: '11:00 AM',
    reason: 'Chronic back pain and nerve compression',
    consultationFee: 900,
    status: 'Upcoming',
    createdAt: '2026-02-14T16:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00024',
    patient_id: 'PAT-2001',
    patientName: 'Suresh Yadav',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-10',
    time: '10:00 AM',
    reason: 'Initial consultation for migraines',
    consultationFee: 900,
    status: 'Completed',
    createdAt: '2026-02-08T08:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00025',
    patient_id: 'PAT-2002',
    patientName: 'Anjali Verma',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-08',
    time: '02:00 PM',
    reason: 'First visit for dizziness symptoms',
    consultationFee: 900,
    status: 'Completed',
    createdAt: '2026-02-06T10:00:00.000Z',
    uploadedMedicalFile: null,
  },
  {
    id: 'APT-00026',
    patient_id: 'PAT-2008',
    patientName: 'Nisha Reddy',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-12',
    time: '03:30 PM',
    reason: 'Stroke risk assessment',
    consultationFee: 900,
    status: 'Completed',
    createdAt: '2026-02-10T11:00:00.000Z',
    uploadedMedicalFile: {
      fileName: 'ct-scan-report.pdf',
      mimeType: 'application/pdf',
      previewUrl: '',
    },
  },
  {
    id: 'APT-00027',
    patient_id: 'PAT-2009',
    patientName: 'Rohit Joshi',
    doctor_id: 'doctor-garvit-001',
    doctorId: 'doctor-garvit-001',
    hospital_id: 'hosp-3',
    doctorName: 'Dr. Garvit Pathania',
    department: 'Neurology',
    date: '2026-02-13',
    time: '01:00 PM',
    reason: 'Sleep disorder consultation',
    consultationFee: 900,
    status: 'Cancelled',
    createdAt: '2026-02-11T09:00:00.000Z',
    uploadedMedicalFile: null,
  },
];

// Function to get appointments by hospital ID
export function getAppointmentsByHospital(hospitalId) {
  return sampleAppointments.filter((appointment) => appointment.hospital_id === hospitalId);
}

// Function to get appointments by status
export function getAppointmentsByStatus(status) {
  return sampleAppointments.filter((appointment) => appointment.status === status);
}

// Function to get today's appointments for a hospital
export function getTodaysAppointments(hospitalId) {
  const today = new Date().toISOString().slice(0, 10);
  return sampleAppointments.filter(
    (appointment) => appointment.hospital_id === hospitalId && appointment.date === today
  );
}
