const coreLegalClauses = [
  'These Terms and Conditions constitute a legally binding agreement between the patient user and Prognosis Care regarding use of the Platform and associated healthcare coordination services.',
  'By creating an account, the user confirms legal capacity to contract under applicable law and confirms all registration details are true, accurate, complete, and not misleading.',
  'The Platform provides informational, triage-support, scheduling, emergency simulation, records-view, and communication facilitation tools and does not itself operate as a licensed hospital.',
  'Any AI-generated output is advisory in nature, intended for preliminary assistance, and shall not be interpreted as definitive diagnosis, prescription, or substitute for in-person medical evaluation.',
  'Clinical decisions, treatment plans, medication choices, and emergency interventions remain solely under the authority of qualified medical professionals and licensed healthcare institutions.',
  'The user agrees to immediately seek emergency care or call local emergency services in the event of severe symptoms including chest pain, breathing distress, stroke signs, trauma, or collapse.',
  'The user acknowledges that delayed care based solely on digital guidance may increase medical risk, and the Platform disclaims liability for outcomes caused by delayed professional consultation.',
  'The user consents to collection, storage, processing, and transmission of personal data, health data, usage telemetry, and communications for service delivery and lawful compliance purposes.',
  'Sensitive health information may be processed only for valid service objectives including triage generation, booking facilitation, profile continuity, safety monitoring, and support resolution.',
  'The Platform shall implement reasonable technical and organizational safeguards, but no networked system can be guaranteed fully immune from unauthorized access or cyber intrusion.',
  'The user is responsible for maintaining account credential confidentiality and shall promptly report suspected unauthorized access, credential compromise, or session misuse.',
  'All activity conducted through an authenticated account is presumed authorized by the account holder unless proven otherwise through verifiable security review.',
  'The Platform may suspend, restrict, or terminate access where fraud, abuse, policy violations, harmful conduct, illegal activity, or security threats are reasonably suspected.',
  'Hospital onboarding, hospital administrator approvals, and provider visibility are subject to internal review workflows and may be changed, delayed, limited, or revoked without prior notice.',
  'The user agrees not to upload unlawful, defamatory, abusive, harmful, infringing, malicious, or medically fabricated information through any form fields, records module, or communications.',
  'The user shall not reverse engineer, scrape, exploit, benchmark, mirror, republish, or commercially reuse any part of the Platform without explicit written authorization.',
  'The Platform may revise AI models, route logic, emergency simulation behavior, user-interface flows, or decision heuristics to improve safety, compliance, and user experience.',
  'Service availability is provided on an as-available and as-is basis and may be interrupted by maintenance windows, third-party outages, network failures, or force majeure events.',
  'The Platform does not warrant uninterrupted operation, absolute accuracy of third-party map layers, or guaranteed timing for estimated arrivals, notifications, or booking confirmations.',
  'Estimated times, simulated ambulance movement, route previews, and map overlays are informational approximations unless explicitly designated as operational emergency dispatch services.',
  'The user acknowledges that geolocation, geocoding, and route outputs may vary by provider availability, map freshness, traffic assumptions, and external API constraints.',
  'Payment references, billing previews, and estimated costs are indicative unless and until validated by hospital billing systems and confirmed through lawful transaction records.',
  'Insurance references shown in the Platform do not constitute insurer approval and remain subject to policy terms, exclusions, eligibility, and payer-side adjudication.',
  'The user grants limited permission for platform notifications regarding care reminders, booking updates, report availability, payment statuses, and urgent safety advisories.',
  'The user may opt out of non-essential communications where applicable, but critical safety or account-security notices may still be delivered where legally permitted.',
  'Any healthcare provider listed on the Platform remains independently responsible for professional licensing, credentials, care quality, and treatment conduct.',
  'The Platform does not assume vicarious liability for independent clinical judgments of hospitals, doctors, laboratories, emergency responders, or third-party service providers.',
  'Medical records uploaded by the user must be lawfully owned or lawfully controlled by the user, and the user bears responsibility for upload legitimacy and data authenticity.',
  'The user shall not submit another individual’s personal health information without valid authority, consent, or legal basis recognized under applicable privacy frameworks.',
  'Where minors or dependent patients are represented, the registering user confirms lawful guardian authority and accepts full responsibility for submitted information accuracy.',
  'The Platform may retain audit logs, policy acknowledgements, consent timestamps, and user action trails for compliance verification, safety investigation, and dispute resolution.',
  'The user acknowledges that anonymized and aggregated analytics may be used to improve AI safety, product reliability, care pathways, and health operations insights.',
  'No content in the Platform shall be interpreted as creating a physician-patient relationship between the user and the Platform operator absent explicit provider engagement.',
  'The user agrees that final triage outcomes must be clinically validated where symptoms are persistent, worsening, severe, atypical, or associated with high-risk comorbidities.',
  'The Platform may require re-authentication, device verification, or additional checks to protect account integrity and prevent unauthorized profile access.',
  'In case of conflict between a hospital policy and these terms for operational care delivery, applicable law and mandatory clinical governance requirements shall prevail.',
  'The user accepts responsibility to keep profile information current including contact details, emergency contacts, and critical medical background data where requested.',
  'The user understands that deletion requests may be limited where retention is legally required for regulatory audit, medical safety, fraud prevention, or contractual necessity.',
  'If any provision of these terms is found unenforceable, remaining provisions shall remain in full force and effect to the maximum extent legally permissible.',
  'Failure by the Platform to enforce any term on one occasion shall not constitute waiver of rights to enforce the same or related terms at any later time.',
  'The user agrees to indemnify and hold harmless the Platform operator against losses arising from misuse, unlawful uploads, rights violations, or material misrepresentation.',
  'Liability, where not excluded by law, shall be limited to direct damages reasonably foreseeable and proven, excluding consequential, indirect, punitive, or special losses.',
  'The Platform reserves the right to update these terms periodically, and continued use after publication of revised terms constitutes acceptance of such revisions.',
  'Where required by law, explicit renewed acceptance may be requested before continued account access following material policy or compliance updates.',
  'Governing law and dispute venue shall be determined by the applicable jurisdiction stated in service documentation, subject to non-excludable consumer rights.',
  'Before formal dispute action, parties agree to attempt good-faith resolution through written notice and reasonable cure period where practicable.',
  'All intellectual property rights in platform software, design systems, models, content structure, and branding remain vested in the rightful owners.',
  'The user receives a limited, non-exclusive, revocable, non-transferable license to access and use the Platform solely for personal, lawful healthcare support purposes.',
  'The user shall not circumvent access controls, interfere with service operations, inject malicious code, or attempt unauthorized elevation of privileges.',
  'Any third-party service integrations, including maps, authentication, communication, and analytics providers, remain subject to their own independent terms and constraints.',
  'The Platform may display third-party content and links for convenience without endorsing, warranting, or assuming responsibility for third-party accuracy or conduct.',
  'The user agrees to cooperate with reasonable verification requests necessary for account recovery, fraud prevention, and safeguarding medically sensitive data.',
  'Where clinical urgency is detected, the Platform may present safety escalations encouraging immediate emergency contact rather than continued digital interaction.',
  'The user confirms understanding that risk stratification labels are probabilistic indicators and must not be interpreted as certainty or exclusion of serious disease.',
  'Hospital appointment slots displayed are subject to change by provider operations and are not guaranteed until confirmed by final scheduling response.',
  'Report availability timelines are estimates and may vary due to laboratory processing complexity, quality controls, specialist validation, or operational backlog.',
  'The Platform may verify uploaded content format, scan for malware, and reject files that violate safety, integrity, or permitted-file standards.',
  'The user agrees not to automate high-frequency requests that degrade system performance, impair fairness, or interfere with safe clinical workflow coordination.',
  'Where authentication is unavailable due to provider outages, the Platform may use controlled fallback modes without guaranteeing parity of all account features.',
  'The user acknowledges that country-specific medical protocols may differ and agrees that local licensed clinician judgment prevails over generalized digital suggestions.',
  'For transparency, key user actions may be timestamped and linked to device/session metadata to support auditability and lawful incident response.',
  'The user may request correction of inaccurate account data, subject to reasonable verification and constraints of immutable clinical audit requirements.',
  'The Platform may conduct quality assurance reviews of AI outputs to reduce unsafe recommendations and improve symptom interpretation consistency over time.',
  'Access to administrative or privileged features is role-restricted and unauthorized attempts to access protected routes or data are strictly prohibited.',
  'The user acknowledges that simulation features are educational and demonstrative unless expressly marked as operational integrations with licensed responders.',
  'In emergency simulation contexts, displayed route, dispatch state, and estimated arrival are for demonstration and must not be relied upon as real dispatch confirmation.',
  'The user accepts that typographical errors, model limitations, and occasional service inaccuracies may occur despite quality controls and safety guardrails.',
  'Where legal obligations require, the Platform may disclose relevant information to lawful authorities, courts, regulators, or emergency agencies.',
  'These terms include all platform policies incorporated by reference, including privacy, acceptable use, data retention, consent handling, and security practices.',
  'If the user does not agree to these terms in full, the user must not create an account and must discontinue use of the Platform immediately.',
  'By selecting acceptance and proceeding, the user confirms informed consent to these terms and acknowledges understanding of rights, obligations, and limitations.',
];

export function getExtendedTermsAndConditionsLines(totalLines = 500) {
  const lines = [];
  for (let index = 1; index <= totalLines; index += 1) {
    const template = coreLegalClauses[(index - 1) % coreLegalClauses.length];
    lines.push(`Clause ${index}. ${template}`);
  }
  return lines;
}
